---
Description: VPC with three public subnets in three availability zones.

Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resources.
    Type: String

  ApplicationName:
    Description: Application Name
    Type: String
      
Resources:
  AppCodeDeploy:
    Type: AWS::CodeDeploy::Application
    Properties:
      ApplicationName: !Join [ "", [ !Ref ApplicationName, CodeDeploy ] ]
      ComputePlatform: Server

  AppCodeDeployGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      ApplicationName: !Join [ "", [ !Ref ApplicationName, CodeDeploy ] ]
      DeploymentGroupName: !Join [ "", [ !Ref ApplicationName, DeploymentGroup ] ]
      ServiceRoleArn:
        Fn::ImportValue: !Join [ "-", [ !Ref InfrastructureName, CodeDeployRoleArn ] ]

  AppCodeDeployConfig:
    Type: AWS::CodeDeploy::DeploymentConfig
    Properties:
      DeploymentConfigName: !Join [ "", [ !Ref ApplicationName, CodeDeployConfig ] ]
      MinimumHealthyHosts: 

Outputs:
  VPC:
    Description: A reference to the VPC.
    Value: !Ref VPC
    Export: { Name: !Join [ "-", [ !Ref AWS::StackName, VpcId ] ] }

#  AvailabilityZones:
#   Description: Availability Zones for this VPC.
#    Value: !Join [ ",", [
#        !GetAtt PublicSubnet1.AvailabilityZone,
#        !GetAtt PublicSubnet2.AvailabilityZone,
#        !GetAtt PublicSubnet3.AvailabilityZone
#    ]]
#    Export: { Name: !Join [ "-", [ !Ref AWS::StackName, Azs ] ] }

  PublicSubnets:
    Description: A list of the public subnets
    Value: !Join [ ",", [ !Ref PublicSubnet1, !Ref PublicSubnet2, !Ref PublicSubnet3 ]]
    Export: { Name: !Join [ "-", [ !Ref AWS::StackName, SubnetIds ] ] }

  PublicSubnet1:
    Description: A reference to the first public subnet.
    Value: !Ref PublicSubnet1

  PublicSubnet2:
    Description: A reference to the first public subnet.
    Value: !Ref PublicSubnet2

  PublicSubnet3:
    Description: A reference to the first public subnet.
    Value: !Ref PublicSubnet3
...
